#!/bin/sh
name=$1
test -z $name && echo "![ERROR] - Repository name required!" 1>&2 && exit 1
curl -i -H "Authorization: token <GITHUB_TOKEN>" -d '{"name":"'$name'", "auto_init": false, "private": true }' https://api.github.com/user/repos > /dev/null

git init
tee README.md << EOF
# REPOSITORY CREATED BY COMANDLINE
EOF
git add README.md
git commit -m "initial commit"
git remote add origin git@github.com:matheusf0/$name.git
git push -f --set-upstream origin master
